# fly.toml app configuration file generated for deployed-dashboard-sparkling-sunset-4809 on 2025-06-09T11:53:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deployed-dashboard-sparkling-sunset-4809'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8050
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
